### HEALTHCHECK
GET {{BASE_URL}}/v1/healthcheck

### POST MOVIES
POST {{BASE_URL}}/v1/movies
Content-Type: application/json

{
  "title": "Moana",
  "year": 2000,
  "runtime": "107 mins",
  "genres": ["Animation", "Adventure", "Comedy"]
}

### GET MOVIES
GET {{BASE_URL}}/v1/movies?genres=animation,adventure

### GET MOVIES BY ID
GET {{BASE_URL}}/v1/movies/1

### PATCH MOVIES BY ID
PUT {{BASE_URL}}/v1/movies/1
Content-Type: application/json

{
  "year": 2016
}

### DELETE MOVIES BY ID
DELETE {{BASE_URL}}/v1/movies/1


### POST USERS
POST {{BASE_URL}}/v1/users
Content-Type: application/json

{
  "name": "Alice Smith",
  "email": "alice@example.com",
  "password": "pa55word"
}

### Activate Account
PUT {{BASE_URL}}/v1/users/activated
Content-Type: application/json

{
  "token": "ZN7YLFYWHQQZTGXCJN2JDPLONI"
}

### Authenticate User
POST {{BASE_URL}}/v1/tokens/authentication
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "pa55word"
}