### HEALTHCHECK
GET {{BASE_URL}}/v1/healthcheck

### POST MOVIES
POST {{BASE_URL}}/v1/movies
Content-Type: application/json

{
  "title": "Moana",
  "year": 1000,
  "runtime": "107 mins",
  "genres": ["sci-fi","sci-fi"]
}

### GET MOVIES BY ID
GET {{BASE_URL}}/v1/movies/1